// Scaffold generated by Meno's JSON → meno-astro converter.
// Minimal Astro config — extend with integrations/adapters as needed.
import { defineConfig } from 'astro/config';
import meno from 'meno-astro/integration';

export default defineConfig({
  // meno() maps project.config.json's i18n into Astro's i18n routing and injects the
  // locale middleware (see meno-astro/integration).
  integrations: [meno()],
});
