// Generated by meno-astro (convertProject) — the project component registry used to
// render components embedded in CMS rich text (richTextWithComponents). Keys are
// component names (file basenames — globally unique in a Meno project).
const modules = import.meta.glob('./components/**/*.astro', { eager: true }) as Record<
  string,
  { default: unknown }
>;

export const cmsComponents: Record<string, unknown> = {};
for (const [path, mod] of Object.entries(modules)) {
  // Lazy getter on purpose: this registry sits in an import CYCLE with every component
  // that renders rich text (it imports all components; those import it back). Reading
  // `mod.default` during module evaluation would hit that component's still-uninitialized
  // const (TDZ — "Cannot access before initialization" at build); deferring the read to
  // render time, when every module in the cycle has evaluated, is safe.
  Object.defineProperty(cmsComponents, path.replace(/^.*\//, '').replace(/\.astro$/, ''), {
    get: () => mod.default,
    enumerable: true,
  });
}
